interface Resources {
  "translation": {
    "deleteWarningUsers": "This user will only be deleted from the app. JSON Placeholder does not save changes.",
    "couldNotFindSearchedUsers": "No users were found.",
    "createUser": "Create User",
    "max64": "Maximum 64 characters",
    "max10": "Maximum 10 characters",
    "fieldRequired": "This field is required",
    "onlyNumbers": "Only numeric values are allowed",
    "Create": "Create",
    "Search": "Search",
    "Edit": "Edit",
    "Name": "Name",
    "userName": "Username",
    "Email": "Email",
    "Address": "Address",
    "Phone": "Phone",
    "Website": "Website",
    "Company": "Company",
    "Cancel": "Cancel",
    "Delete": "Delete",
    "deleteSelected": "Delete Selected Items",
    "selectAll": "Select All Items",
    "Street": "Street",
    "Suite": "Suite",
    "City": "City",
    "ZipCode": "Zip Code",
    "companyName": "Company Name",
    "catchPhrase": "Catch Phrase",
    "bs": "Business Specialization",
    "Refresh": "Refresh, it will reset all changes",
    "Users": "Users",
    "phoneNumber": "Phone Number",
    "pickedColor": "Picked Color",
    "Light": "Light",
    "Dark": "Dark",
    "Settings": "Settings",
    "Posts": "Posts",
    "Comments": "Comments"
  }
}

export default Resources;
